name: run-tests

on:
  push:
    branches: master
  pull_request:

jobs:
  test-net50:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.201'
    - run: dotnet test -c "Debug" -f net5.0
    
  test-netcoreapp31:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.407'
    - run: dotnet test -c "Debug" -f netcoreapp31
